-- ModSupport_R2_TEXT
-- Generated from project\localization\ModSupport_R2_TEXT.md by project/tools/localization/loc_md_to_sql.py
-- Edit the Markdown source, then regenerate this file.
--------------------------------------------------------------

INSERT OR REPLACE INTO LocalizedText
    (Language, Tag, Text)
VALUES
    ('en_US', 'LOC_PEDIA_RESOURCES_PAGE_RESOURCE_BERRIES_CHAPTER_CSCQUAR_TITLE', 'Supply Chains'),
    ('en_US', 'LOC_PEDIA_RESOURCES_PAGE_RESOURCE_BERRIES_CHAPTER_CSCQUAR_PARA_1', 'Base material: [ICON_BAKERS] Bakers'' Quarter'),
    ('en_US', 'LOC_PEDIA_RESOURCES_PAGE_RESOURCE_DATES_CHAPTER_CSCQUAR_TITLE', 'Supply Chains'),
    ('en_US', 'LOC_PEDIA_RESOURCES_PAGE_RESOURCE_DATES_CHAPTER_CSCQUAR_PARA_1', 'Base material: [ICON_BAKERS] Bakers'' Quarter'),
    ('en_US', 'LOC_PEDIA_RESOURCES_PAGE_RESOURCE_POPPIES_CHAPTER_CSCQUAR_TITLE', 'Supply Chains'),
    ('en_US', 'LOC_PEDIA_RESOURCES_PAGE_RESOURCE_POPPIES_CHAPTER_CSCQUAR_PARA_1', 'Base material: [ICON_BAKERS] Bakers'' Quarter'),
    ('en_US', 'LOC_PEDIA_RESOURCES_PAGE_RESOURCE_SAFFRON_CHAPTER_CSCQUAR_TITLE', 'Supply Chains'),
    ('en_US', 'LOC_PEDIA_RESOURCES_PAGE_RESOURCE_SAFFRON_CHAPTER_CSCQUAR_PARA_1', 'Base material: [ICON_BAKERS] Bakers'' Quarter'),
    ('en_US', 'LOC_PEDIA_RESOURCES_PAGE_RESOURCE_STRAWBERRY_CHAPTER_CSCQUAR_TITLE', 'Supply Chains'),
    ('en_US', 'LOC_PEDIA_RESOURCES_PAGE_RESOURCE_STRAWBERRY_CHAPTER_CSCQUAR_PARA_1', 'Base material: [ICON_BAKERS] Bakers'' Quarter'),
    ('en_US', 'LOC_PEDIA_RESOURCES_PAGE_RESOURCE_MAPLE_CHAPTER_CSCQUAR_TITLE', 'Supply Chains'),
    ('en_US', 'LOC_PEDIA_RESOURCES_PAGE_RESOURCE_MAPLE_CHAPTER_CSCQUAR_PARA_1', 'Base material: [ICON_BAKERS] Bakers'' Quarter'),
    ('en_US', 'LOC_PEDIA_RESOURCES_PAGE_RESOURCE_TOMATO_CHAPTER_CSCQUAR_TITLE', 'Supply Chains'),
    ('en_US', 'LOC_PEDIA_RESOURCES_PAGE_RESOURCE_TOMATO_CHAPTER_CSCQUAR_PARA_1', 'Base material: [ICON_BAKERS] Bakers'' Quarter');

-- Raw SQL 1
UPDATE LocalizedText
SET Text = Text || '[NEWLINE][ICON_BULLET][ICON_RESOURCE_BARLEY] Barley [NEWLINE][ICON_BULLET][ICON_RESOURCE_SORGHUM] Sorghum'
WHERE Tag='LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_CSC_BAKERS_QUARTER_CHAPTER_CSCBASE_PARA_1';

-- Raw SQL 2
UPDATE LocalizedText
SET Text = Text || '[NEWLINE][ICON_BULLET][ICON_RESOURCE_BERRIES] Berries [NEWLINE][ICON_BULLET][ICON_RESOURCE_DATES] Dates [NEWLINE][ICON_BULLET][ICON_RESOURCE_POPPIES] Poppies [NEWLINE][ICON_BULLET][ICON_RESOURCE_SAFFRON] Saffron [NEWLINE][ICON_BULLET][ICON_RESOURCE_STRAWBERRY] Strawberry [NEWLINE][ICON_BULLET][ICON_RESOURCE_MAPLE] Sugar Maple [NEWLINE][ICON_BULLET][ICON_RESOURCE_TOMATO] Tomato'
WHERE Tag='LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_CSC_BAKERS_QUARTER_CHAPTER_CSCSPEC_PARA_1';
