-- ModSupport_LGD_TEXT
-- Generated from project\localization\ModSupport_LGD_TEXT.md by project/tools/localization/loc_md_to_sql.py
-- Edit the Markdown source, then regenerate this file.
--------------------------------------------------------------

INSERT OR REPLACE INTO LocalizedText
    (Language, Tag, Text)
VALUES
    ('en_US', 'LOC_DISTRICT_CSC_BAKERS_QUARTER_DESCRIPTION', 'A district in your city specializing in baking.[NEWLINE][NEWLINE]+1 [ICON_Production] Production from every 2 adjacent river segments once the Water Mill is built, or +1 [ICON_Production] Production if built on Hills terrain once the Wind Mill is built.'),
    ('en_US', 'LOC_CSC_GARDEN_GOLD_TO_BAKERS', '+{1_num} [ICON_Gold] from the adjacent {1_num : plural 1?Garden; other?Gardens;}.'),
    ('en_US', 'LOC_BUILDING_CSC_BAKERS_CAFE_DESCRIPTION_GARDEN', '+1 [ICON_Food] Food from the local Water Mill or Wind Mill, in exchange for +1 [ICON_Production] Production and +1 [ICON_Gold] Gold.[NEWLINE]+1 [ICON_Food] Food from each adjacent Specialty Materials improvement, in exchange for +1 [ICON_Production] Production.[NEWLINE]+1 [ICON_Citizen] Citizen slot, +1 [ICON_Food] Food and +1 [ICON_Culture] Culture to [ICON_Citizen] Citizens in the Quarter.[NEWLINE]+1 [ICON_Amenities] Amenity to all cities within 6 tiles.[NEWLINE]+1 [ICON_Production] Production and +1 [ICON_Gold] Gold for every 5 [ICON_Citizen] Citizens in the city from each adjacent Zoo, Ferris Wheel and Garden, in exchange for +1 [ICON_Culture] Culture.[NEWLINE]+1 [ICON_Food] Food bonus to [ICON_TradeRoute] Trade Routes to the city, in exchange for +2 [ICON_Gold] Gold to the Quarter, if the origin city does not have a Bakers'' Quarter.[NEWLINE][NEWLINE]At Urbanization, a supplied Café can establish services in adjacent Entertainment Complexes with Zoos, Water Parks with Ferris Wheels and Gardens with Conservatories.'),
    ('en_US', 'LOC_BUILDING_CSC_BAKERS_STAGE_4_SERVICE_GARDEN_NAME', 'Horticulturist'),
    ('en_US', 'LOC_BUILDING_CSC_BAKERS_STAGE_4_SERVICE_GARDEN_DESCRIPTION', 'A Service established in the Garden at Urbanization when a supplied Café serves an adjacent Conservatory, adding tourism and staffing the Garden.[NEWLINE][NEWLINE]+2 [ICON_Tourism] Tourism and +1 [ICON_GreatArtist] Great Artist point.'),
    ('en_US', 'LOC_CSC_BAKERS_STAGE_4_SERVICE_GARDEN', '[NEWLINE]{LOC_BUILDING_CSC_BAKERS_STAGE_4_SERVICE_GARDEN_NAME} service: +2 [ICON_Tourism] Tourism and +1 [ICON_GreatArtist] Great Artist point from each adjacent supplied Café, plus +1 [ICON_Citizen] Citizen slot if the Garden has a Conservatory.'),
    ('en_US', 'LOC_CSC_BAKERS_STAGE_4_EFFECT_GARDEN', '[NEWLINE][NEWLINE]+1 [ICON_Culture] Culture for every 5 [ICON_Citizen] Citizens in the city from each adjacent Café, in exchange for +1 [ICON_Production] Production and +1 [ICON_Gold] Gold to the Café.[NEWLINE][NEWLINE]At Urbanization, a Conservatory adjacent to a supplied Café establishes a {LOC_BUILDING_CSC_BAKERS_STAGE_4_SERVICE_ENTER_NAME} service: +2 [ICON_Tourism] Tourism and +1 [ICON_GreatArtist] Great Artist point from each adjacent supplied Café, plus +1 [ICON_Citizen] Citizen slot in the Garden.'),
    ('en_US', 'LOC_CSC_BAKERS_STAGE_4_CIVIC', 'A Zoo adjacent to a supplied Café establishes a {LOC_BUILDING_CSC_BAKERS_STAGE_4_SERVICE_ENTER_NAME} service, a Ferris Wheel adjacent to a supplied Café establishes a {LOC_BUILDING_CSC_BAKERS_STAGE_4_SERVICE_WATER_NAME} service, and a Garden with a Conservatory adjacent to a supplied Café establishes a {LOC_BUILDING_CSC_BAKERS_STAGE_4_SERVICE_GARDEN_NAME} service:[NEWLINE]+2 [ICON_Tourism] Tourism from each adjacent supplied Café, plus +1 [ICON_Citizen] Citizen slot in the district. Zoo and Ferris Wheel services add +1 [ICON_GreatEngineer] Great Engineer point; Garden services add +1 [ICON_GreatArtist] Great Artist point.'),
    ('en_US', 'LOC_CSC_BAKERS_STAGE_4_EFFECT_DESCRIPTION_GARDEN', '{LOC_BUILDING_CSC_BAKERS_STAGE_4_SERVICE_GARDEN_NAME}: {1_TotalAmount} [ICON_Tourism] Tourism and {2_TotalStack} [ICON_GreatArtist] Great Artist {3_TotalStackCount : plural 1?point; other?points;}.[NEWLINE]Supply Chain: {3_TotalStackCount} supplied {3_TotalStackCount : plural 1?Café; other?Cafés;} [ICON_ARROW] adjacent Conservatory.'),
    ('en_US', 'LOC_CSC_BAKERS_STAGE_4_EFFECT_DESCRIPTION_GARDEN_NEW', 'a new {LOC_BUILDING_CSC_BAKERS_STAGE_4_SERVICE_GARDEN_NAME} service: {1_NewAmount} [ICON_Tourism] Tourism, {2_NewStack} [ICON_GreatArtist] Great Artist {3_StackCount : plural 1?point; other?points;} and +1 [ICON_Citizen] Citizen slot in the Garden'),
    ('en_US', 'LOC_CSC_BAKERS_STAGE_4_EFFECT_DESCRIPTION_GARDEN_INCREASED', '{LOC_BUILDING_CSC_BAKERS_STAGE_4_SERVICE_GARDEN_NAME} service: {1_IncreaseAmount} [ICON_Tourism] Tourism and {2_IncreasedStack} [ICON_GreatArtist] Great Artist {3_StackCount : plural 1?point; other?points;}'),
    ('en_US', 'LOC_CSC_BAKERS_STAGE_4_EFFECT_DESCRIPTION_GARDEN_DECREASED', '{LOC_BUILDING_CSC_BAKERS_STAGE_4_SERVICE_GARDEN_NAME} service: {1_DecreaseAmount} [ICON_Tourism] Tourism and {2_DecreasedStack} [ICON_GreatArtist] Great Artist {3_StackCount : plural 1?point; other?points;}'),
    ('en_US', 'LOC_CSC_BAKERS_STAGE_4_EFFECT_DESCRIPTION_GARDEN_REMOVED', '{LOC_BUILDING_CSC_BAKERS_STAGE_4_SERVICE_GARDEN_NAME} service: {1_LostAmount} [ICON_Tourism] Tourism and {2_LostStack} [ICON_GreatArtist] Great Artist {3_StackCount : plural 1?point; other?points;}'),
    ('en_US', 'LOC_PEDIA_BUILDINGS_PAGE_BUILDING_CSC_BAKERS_CAFE_CHAPTER_HISTORY_PARA_3', 'The sales interaction of a Café with the local Zoo, Ferris Wheel, or Garden is a reflection of the rise of leisure culture and the "day out." As cities grew and the middle class expanded, public entertainment venues became popular destinations. A café adjacent to these attractions would have been a natural fit, offering a place for people to relax and socialize as part of their visit. This connection demonstrates how the Café was not just a place for intellectual discussion, but a vital part of a burgeoning urban entertainment industry, catering to a public seeking new forms of recreation and social engagement.'),
    ('en_US', 'LOC_PEDIA_BUILDINGS_PAGE_BUILDING_CSC_BAKERS_CAFE_CHAPTER_CSCHAIN_PARA_1', 'The Café procures flour from the Water Mill or Wind Mill in the Quarter, as well as various specialty materials from adjacent improvements on those specific resources, and transforms them into fine baked goods and drinks for sale to select customers visiting the adjacent Entertainment Complex, Water Park or Garden.'),
    ('en_US', 'LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_LEU_GARDEN_CHAPTER_CSCHAIN_TITLE', 'Supply Chains'),
    ('en_US', 'LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_LEU_GARDEN_CHAPTER_CSCHAIN_PARA_1', 'Some visitors to the Garden also enjoy refreshments from the adjacent Café.[NEWLINE][NEWLINE]At Urbanization, an adjacent supplied Café can establish a {LOC_BUILDING_CSC_BAKERS_STAGE_4_SERVICE_GARDEN_NAME} service if this district has a Conservatory. See the {LOC_BUILDING_CSC_BAKERS_STAGE_4_SERVICE_GARDEN_NAME} Civilopedia page for full requirements and effects.'),
    ('en_US', 'LOC_PEDIA_BUILDINGS_PAGE_BUILDING_LEU_CONSERVATORY_CHAPTER_CSCHAIN_TITLE', 'Supply Chains'),
    ('en_US', 'LOC_PEDIA_BUILDINGS_PAGE_BUILDING_LEU_CONSERVATORY_CHAPTER_CSCHAIN_PARA_1', 'The Conservatory completes the Garden side of the Bakers'' Quarter service chain, much as the Zoo and Ferris Wheel complete the Entertainment and Water Park sides.[NEWLINE][NEWLINE]At Urbanization, an adjacent supplied Café can establish a {LOC_BUILDING_CSC_BAKERS_STAGE_4_SERVICE_GARDEN_NAME} service in this Garden: +2 [ICON_Tourism] Tourism and +1 [ICON_GreatArtist] Great Artist point from each adjacent supplied Café, plus +1 [ICON_Citizen] Citizen slot in the district.'),
    ('en_US', 'LOC_PEDIA_BUILDINGS_PAGE_BUILDING_CSC_BAKERS_STAGE_4_SERVICE_GARDEN_CHAPTER_CSCHAIN_TITLE', 'Supply Chains'),
    ('en_US', 'LOC_PEDIA_BUILDINGS_PAGE_BUILDING_CSC_BAKERS_STAGE_4_SERVICE_GARDEN_CHAPTER_CSCHAIN_PARA_1', 'The Café draws on dependable flour from the local Water Mill or Wind Mill and improved Bakers'' specialty materials nearby, turns them into pastries and drinks, and offers that steady flow of refreshments to the growing numbers of visitors to the adjacent Conservatory.[NEWLINE][NEWLINE]This gives a Citizen the opportunity to take up employment as a Horticulturist in the Garden, tending rare plants, guiding curious visitors, and keeping the living collection healthy enough to become part of the city''s public life.'),
    ('en_US', 'LOC_PEDIA_BUILDINGS_PAGE_BUILDING_CSC_BAKERS_STAGE_4_SERVICE_GARDEN_CHAPTER_HISTORY_TITLE', 'Historical Context'),
    ('en_US', 'LOC_PEDIA_BUILDINGS_PAGE_BUILDING_CSC_BAKERS_STAGE_4_SERVICE_GARDEN_CHAPTER_HISTORY_PARA_1', 'Public gardens became more than pleasant green spaces when growing cities had the wealth and leisure to maintain them as destinations. Conservatories added spectacle: rare plants, glasshouse engineering, careful climates, and a steady stream of curious visitors. Cafés made those visits longer and more social, turning a stroll among plants into an afternoon out. The horticulturist is the quiet professional behind that transformation, keeping the living attraction alive while the city learns to treat leisure as part of urban life.');

-- Raw SQL 1
UPDATE LocalizedText
SET Text = Text || '[NEWLINE][ICON_BULLET][ICON_DISTRICT_LEU_GARDEN] {LOC_DISTRICT_LEU_GARDEN_NAME}'
WHERE Tag = 'LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_CSC_BAKERS_QUARTER_CHAPTER_CSCSALES_PARA_1';
