-- CSC_MC_MODE_TEXT
-- Author: Henno
-- DateCreated: 2025-08-09 18:24:19
--------------------------------------------------------------

-- M&C Industry/Corporation wording only. Specialty Products text moved to Taxes And Politics.

UPDATE LocalizedText
SET Text = '+1 [ICON_Food] Food from each adjacent Base Materials improvement, increased to +2 [ICON_Food] Food from an Industry and +3 [ICON_Food] Food from a Corporation, in exchange for +1 [ICON_Production] Production and +1 [ICON_Gold] Gold, increased to +2 each for an Industry and +3 each for a Corporation.[NEWLINE]+1 [ICON_Production] Production and +1 [ICON_Gold] Gold from the local Bakery and Café, in exchange for +1 [ICON_Food] Food.[NEWLINE]+1 [ICON_Production] Production and +1 [ICON_Gold] Gold from an adjacent Granary, in exchange for +1 [ICON_Food] Food.[NEWLINE]+1 [ICON_Food] Food bonus to [ICON_TradeRoute] Trade Routes to the city, in exchange for +1 [ICON_Production] Production and +1 [ICON_Gold] Gold to the Quarter, if the origin city does not have a Bakers'' Quarter.[NEWLINE][NEWLINE]At Feudalism, a supplied Water Mill or Wind Mill can establish a {LOC_BUILDING_CSC_BAKERS_STAGE_2_SERVICE_NAME} service in an adjacent City Center with a Granary.'
WHERE Tag = 'LOC_BUILDING_CSC_BAKERS_WATER_MILL_DESCRIPTION' OR Tag = 'LOC_BUILDING_CSC_BAKERS_WIND_MILL_DESCRIPTION';

UPDATE LocalizedText
SET Text = '+1 [ICON_Food] Food from each adjacent Specialty Materials improvement, increased to +2 [ICON_Food] Food from an Industry and +3 [ICON_Food] Food from a Corporation, in exchange for +1 [ICON_Production] Production, increased to +2 [ICON_Production] Production to an Industry and +3 [ICON_Production] Production to a Corporation.[NEWLINE]+1 [ICON_Citizen] Citizen slot, +1 [ICON_Food] Food and +1 [ICON_Culture] Culture to [ICON_Citizen] Citizens in the Quarter.[NEWLINE]+1 [ICON_Food] Food from the local Water Mill or Wind Mill, in exchange for +1 [ICON_Production] Production and +1 [ICON_Gold] Gold.[NEWLINE]+1 [ICON_Culture] Culture to each adjacent Zoo and Ferris Wheel for every 5 [ICON_Citizen] Citizens in the city, in exchange for +1 [ICON_Production] Production and +1 [ICON_Gold] Gold to the Café for every 5 [ICON_Citizen] Citizens in each adjacent Zoo or Ferris Wheel city.[NEWLINE]+1 [ICON_Food] Food bonus to [ICON_TradeRoute] Trade Routes to the city, in exchange for +1 [ICON_Production] Production and +2 [ICON_Gold] Gold to the Quarter, if the origin city does not have a Bakers'' Quarter.[NEWLINE][NEWLINE]At Urbanization, a supplied Café can establish services in adjacent Entertainment Complexes with Zoos and Water Parks with Ferris Wheels.'
WHERE Tag = 'LOC_BUILDING_CSC_BAKERS_CAFE_DESCRIPTION';

UPDATE LocalizedText
SET Text = '+1 [ICON_Food] Food from each adjacent Specialty Materials improvement, increased to +2 [ICON_Food] Food from an Industry and +3 [ICON_Food] Food from a Corporation, in exchange for +1 [ICON_Production] Production, increased to +2 [ICON_Production] Production to an Industry and +3 [ICON_Production] Production to a Corporation.[NEWLINE]+1 [ICON_Citizen] Citizen slot, +1 [ICON_Food] Food and +1 [ICON_Culture] Culture to [ICON_Citizen] Citizens in the Quarter.[NEWLINE]+1 [ICON_Food] Food from the local Water Mill or Wind Mill, in exchange for +1 [ICON_Production] Production and +1 [ICON_Gold] Gold.[NEWLINE]+1 [ICON_Culture] Culture to each adjacent Zoo, Ferris Wheel, and Conservatory for every 5 [ICON_Citizen] Citizens in the city, in exchange for +1 [ICON_Production] Production and +1 [ICON_Gold] Gold to the Café for every 5 [ICON_Citizen] Citizens in each adjacent Zoo, Ferris Wheel, or Conservatory city.[NEWLINE]+1 [ICON_Food] Food bonus to [ICON_TradeRoute] Trade Routes to the city, in exchange for +1 [ICON_Production] Production and +2 [ICON_Gold] Gold to the Quarter, if the origin city does not have a Bakers'' Quarter.[NEWLINE][NEWLINE]At Urbanization, a supplied Café can establish services in adjacent Entertainment Complexes with Zoos, Water Parks with Ferris Wheels, and Gardens with Conservatories.'
WHERE Tag = 'LOC_BUILDING_CSC_BAKERS_CAFE_DESCRIPTION_GARDEN';
